[package]
name = "creek"
version = "0.1.0"
edition = "2024"

[features]
use_luajit = ["mlua"]
use_vulkan = ["ash", "ash-window", "image", "winit"]
use_rodio = ["rodio"]

[dependencies]
ash = { version = "0.38.0", optional = true, default-features = false, features = ["linked", "debug", "std"] }
ash-window = { version = "0.13.0", optional = true }
image = { version = "0.25.9", optional = true, default-features = false, features = ["png"] }
mlua = { version = "0.9", optional = true, features = ["luajit", "send"] }
rodio = { version = "0.21.1", optional = true }
winit = { version = "0.30.12", optional = true, features = ["rwh_06"] }